language: python
sudo: false
python:
    - "3.6"
    - "3.7"
    - "3.8"
install:
    - pip install -U pip wheel coverage codecov
    - pip install -r requirements_dev.txt
    - python setup.py develop
script:
    - flake8 sepaxml tests
    - isort -rc -c sepaxml
    - coverage run -m py.test -v tests/ && codecov
cache:
    directories:
        - $HOME/.cache/pip
